apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "foodlens-ai.fullname" . }}-config
  labels:
    {{- include "foodlens-ai.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.config.nodeEnv | quote }}
  MOCK_EXTERNAL_SERVICES: {{ .Values.config.mockExternalServices | quote }}
  AUTH_SERVICE_URL: "http://{{ include "foodlens-ai.fullname" . }}-auth-service:3001"
  IMAGE_SERVICE_URL: "http://{{ include "foodlens-ai.fullname" . }}-image-service:3002"
  FOOD_SERVICE_URL: "http://{{ include "foodlens-ai.fullname" . }}-food-service:3003"
  NUTRITION_SERVICE_URL: "http://{{ include "foodlens-ai.fullname" . }}-nutrition-service:3004"
  ANALYSIS_SERVICE_URL: "http://{{ include "foodlens-ai.fullname" . }}-analysis-service:3005"
  RECOMMENDATION_SERVICE_URL: "http://{{ include "foodlens-ai.fullname" . }}-recommendation-service:3006"
