{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "foodlens-ai.fullname" . }}-ingress
  labels:
    {{- include "foodlens-ai.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - host: {{ .Values.ingress.hosts.frontend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "foodlens-ai.fullname" . }}-frontend
                port:
                  number: 80
    - host: {{ .Values.ingress.hosts.gateway }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "foodlens-ai.fullname" . }}-api-gateway
                port:
                  number: 3000
{{- end }}
