apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foodlens-ai.fullname" . }}-secrets
  labels:
    {{- include "foodlens-ai.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secrets.databaseUrl | quote }}
  REDIS_URL: {{ .Values.secrets.redisUrl | quote }}
  RABBITMQ_URL: {{ .Values.secrets.rabbitmqUrl | quote }}
  JWT_ACCESS_SECRET: {{ .Values.secrets.jwtAccessSecret | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secrets.jwtRefreshSecret | quote }}
