export enum AnalysisStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  FOOD_RECOGNITION = 'FOOD_RECOGNITION',
  NUTRITION = 'NUTRITION',
  HEALTH_ANALYSIS = 'HEALTH_ANALYSIS',
  RECOMMENDATIONS = 'RECOMMENDATIONS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum SourceType {
  NUTRITION = 'NUTRITION',
  HEALTH = 'HEALTH',
  RECIPE = 'RECIPE',
  OTHER = 'OTHER',
}

export enum EventType {
  FOOD_ANALYSIS_REQUESTED = 'FOOD_ANALYSIS_REQUESTED',
  FOOD_RECOGNIZED = 'FOOD_RECOGNIZED',
  NUTRITION_REQUESTED = 'NUTRITION_REQUESTED',
  NUTRITION_COMPLETED = 'NUTRITION_COMPLETED',
  HEALTH_ANALYSIS_REQUESTED = 'HEALTH_ANALYSIS_REQUESTED',
  HEALTH_ANALYSIS_COMPLETED = 'HEALTH_ANALYSIS_COMPLETED',
  RECOMMENDATIONS_REQUESTED = 'RECOMMENDATIONS_REQUESTED',
  RECOMMENDATIONS_COMPLETED = 'RECOMMENDATIONS_COMPLETED',
  FOOD_ANALYSIS_COMPLETED = 'FOOD_ANALYSIS_COMPLETED',
  FOOD_ANALYSIS_FAILED = 'FOOD_ANALYSIS_FAILED',
}
