apiVersion: v1
kind: Service
metadata:
  name: {{ include "foodlens-ai.fullname" . }}-recommendation-service
  labels:
    app: recommendation-service
    {{- include "foodlens-ai.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.services.recommendationService.port }}
      targetPort: {{ .Values.services.recommendationService.port }}
      protocol: TCP
      name: http
  selector:
    app: recommendation-service
